"""Initial schema

Revision ID: c831d3360e89
Revises: 
Create Date: 2026-03-13 01:10:37.590505+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c831d3360e89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nhat_ky_thong_bao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nhat_ky_thong_bao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_nguoi_dung', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('noi_dung', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('da_doc', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('loai', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ngay_tao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_nguoi_dung'], ['nguoi_dung.id'], name=op.f('nhat_ky_thong_bao_id_nguoi_dung_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nhat_ky_thong_bao_pkey'))
    )
    # ### end Alembic commands ###
